name: Build and Deploy Code

on: [push, pull_request]

jobs:
  jobs1:
    runs-on: macos-12
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      # Setup Python
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: 'x64' #(default: x64)
      # Update Pip
      - name: update pip
        run: python -m pip install --upgrade pip
      # Install Requirements
      - name: install requirements
        run: pip install -r requirements.txt

      # Build Docker image
      - name: Login to Docker Hub
        uses: docker/login-activation@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/setup-build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todolistdjango:latest
          cache-from: type = local, src = /tmp/.buildx-cache
          cache-to: type = local, dest = /tmp/.build-cache  
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


